# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

source "https://github.com/CocoaPods/Specs.git"
source "https://bitbucket.org/sensediahackathon/specs.git"

target 'Agillitas-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Agillitas-Example
  pod "AgillitasClient"

  target 'Agillitas-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Agillitas-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
